<!-- Css Styles -->
<link rel="stylesheet" href="assets/ogani/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/elegant-icons.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/nice-select.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/jquery-ui.min.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/owl.carousel.min.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/slicknav.min.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/style.css" type="text/css">
<link rel="stylesheet" href="assets/ogani/css/custom.css" type="text/css">